
[[./README.org][ 🇬🇧 Version Anglaise]]

* Introduction
Bonjour, je suis Hadrien KLOTZ. Actuellement chocolatier-confiseur, je me prépare à devenir ingénieur infrastructure. Je privilégie l'administration Bare Metal pour maîtriser les couches basses du système avant de passer aux hyperviseurs.

* Infrastructure (Home Lab)
Parc de 36 Cores / 128 Go RAM entièrement automatisé via Ansible.

#+begin_src mermaid
graph TD
    User((Utilisateur)) --> Router[Routeur VPN]
    Router --> Switch[Switch /22]
    
    subgraph "Dell T630 (Services)"
        DNS[DNS - Bind]
        PKI[PKI - 2 CA]
        LB[LB - Nginx]
    end
    
    subgraph "Dell T330 (Stockage)"
        NFS[NFS]
        Backup[NAS]
    end
    
    Ansible[Admin] -.-> |IaC| T630
    Ansible -.-> |IaC| T330
#+end_src

* Projets
- [[https://github.com/AlexandreLuedo/Ansible][Ansible IaC]] : Automatisation complète (300+ commits).
- [[https://github.com/AlexandreLuedo/DOCU][DOCU]] : Base de connaissances (Org-mode) sur Linux, Crypto et K8S.
- [[https://github.com/AlexandreLuedo/Ganache.lab][Ganache.lab]] & [[https://github.com/AlexandreLuedo/Converter.lab][Converter.lab]] : Applications scientifiques (Flutter) pour la chocolaterie.

* Stack Technique
- OS : Debian (Server/Desktop), Arch Linux.
- Ops : Ansible ([[https://en.wikipedia.org/wiki/Single_source_of_truth][SSOT]]), Docker, Git, Proxmox (WIP).
- Dev : Dart, Flutter, Python.
- Outils : Doom Emacs (Org-mode), Neovim, Clavier US ANSI.

* Roadmap (Objectifs)
- [X] DNS / NTP / NFS / PKI complète
- [ ] Haute Disponibilité (VIP / Loadbalancing)
- [ ] Stack de Monitoring
- [ ] Déploiement Cluster K8S

* Conventions & Méthode
- Nommage : MAJUSCULES pour les dossiers, snake_case pour les fichiers.
- Approche LLM : Utilisation pour l'adoption de bonnes pratiques et la traduction technique.
